(ns clojure.core.typed.test.runtime-infer.fixed-varargs
  {:lang :core.typed
   :core.typed {:features #{:runtime-infer}}
   }
  (:require [clojure.core.typed :as t]
            [clojure.spec.alpha :as s]
            [clojure.pprint :refer [pprint]]))

;; Start: Generated by clojure.core.typed - DO NOT EDIT
(s/fdef
  function
  :args
  (s/alt
    :2-args
    (s/cat :i int? :f int?)
    :3-args
    (s/cat :i int? :j int? :k int?))
  :ret
  int?)
;; End: Generated by clojure.core.typed - DO NOT EDIT

(defn function 
  ([i f] (function i f 0))
  ([i j & [k]]
   i))

(function 1 2)
(function 1 2 3)
