(ns clojure.core.typed.test.runtime-infer.qualified-keys
  {:lang :core.typed
   :core.typed {:features #{:runtime-infer}}
   }
  (:require [clojure.core.typed :as t]
            [clojure.pprint :refer [pprint]]))

;; Start: Generated by clojure.core.typed - DO NOT EDIT
(s/def ::Foo1Map (s/keys :req [::foo1]))
(s/def ::foo (s/or :nil? nil? :FooMap ::FooMap :Foo1Map ::Foo1Map))
(s/def ::foo2 (s/and ::FooMap))
(s/def ::FooMap (s/keys :req [::foo]))
(s/fdef qualified :args (s/cat) :ret ::FooMap)
(s/def ::Foo2Map (s/keys :req [::foo2]))
(s/fdef qualified2 :args (s/cat) :ret ::Foo2Map)
(s/def :keys94094/foo (s/or :nil? nil? :FooMap__94064 ::FooMap__94064))
(s/def ::FooMap__94064 (s/keys :req-un [:keys94094/foo]))
(s/fdef unqualified :args (s/cat) :ret ::FooMap__94064)
;; End: Generated by clojure.core.typed - DO NOT EDIT

(defn unqualified []
  {:foo {:foo {:foo nil}}}
  )
(defn qualified []
  {::foo {::foo {::foo nil}}}
  )

(defn qualified2 []
  {::foo2 {::foo {::foo1 nil}}}
  )

(defn same1 []
  {:blah 1
   :flag 2
   :opt1 2
   :opt2 3})

(defn same2 []
  {:blah 1
   :flag 2
   :opt1 2
   :opt3 3})

(qualified)
(qualified2)
(unqualified)
;(same1)
;(same2)