#!/bin/sh

# Usage:
# ./script/add-copyright module-rt/src/main/clojure/cljs/core/typed.clj
#
# Note: must be executed at root of repository.

FILE=$1
COPYRIGHT=";;   Copyright (c) Ambrose Bonnaire-Sergeant, Rich Hickey & contributors.
;;   The use and distribution terms for this software are covered by the
;;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
;;   which can be found in the file epl-v10.html at the root of this distribution.
;;   By using this software in any fashion, you are agreeing to be bound by
;;   the terms of this license.
;;   You must not remove this notice, or any other, from this software.

"

if [ -z "$FILE" ]; then
  echo "Must provide file name"
  exit 1;
fi

# explanation: https://superuser.com/a/1063882
ex -s -c '1i|'"$COPYRIGHT" -c x $FILE
