#!/bin/bash

set -e

VERSION=$1

if [ -z "$VERSION" ]
  then
    echo "No new version supplied"
    echo "usage: ./script/bump-readme-version <NEW-VERSION>"
    exit 1
fi

./script/bump-readme-version.clj "$VERSION" README.md typed/analyzer.jvm/README.md typed/annotator.jvm/README.md typed/checker.jvm/README.md typed/lang.jvm/README.md typed/lib.clojure/README.md typed/runtime.jvm/README.md
