#!/bin/sh

# USAGE: ./test-local-clj PROJECT CLOJURE_VERSION
# eg. ./test-local-clj core.typed.checker.jvm 1.9.0

set -e

PROJECT=$1
CLJ=$2

if [ -z $PROJECT ]; then
  echo "Must provide project as first argument"
  exit 1
fi
if [ -z $CLJ ]; then
  echo "Must provide Clojure version as second argument"
  exit 1
fi

cd $PROJECT
echo "PROJECT: $PROJECT (Clojure $CLJ)"
CLJ_CONFIG="../common" bash -c "./script/test -A:local-deps -J-Xmx2g -Sdeps '{:deps {org.clojure/clojure {:mvn/version \"$CLJ\"}}}'" # -Stree
cd ..
